added function show (#10)
* udpated GetInstance
* added function Show

Co-authored-by: dzaiets <lpde4590>

diff --git a/bin/awpt b/bin/awpt
--- a/bin/awpt
+++ b/bin/awpt
@@ -191,52 +191,35 @@ ConfigGet() {
   ConfigGetResult=$(grep "^${param}" ${ProjectConfig} 2>/dev/null | awk -F= '{print $2}' | head -1)
 }
 #
-ListInstancesByPattern() {
-  local pattern=$1
-  if [ -z "${pattern}" ]; then
-    return
-  fi
-  #
-  if grep -q "${pattern}" ${awsEC2list} 2>/dev/null; then
-    echo -e "\nPerhaps you means:"
-    grep -i "${pattern}" ${awsEC2list} 2>/dev/null | awk '{print $2,$3}' | sort
-    echo ""
-  fi
-}
-#
 GetInstance() {
   GetCurrentProject
   SetProjectVars
-  local name=$1
-  if [ -z "${name}" ]; then
+  local pattern=$1
+  local ec2_id
+  local ec2_name
+  local result
+  if [ -z "${pattern}" ]; then
     error "function: GetInstance, parameter is EMPTY"
   fi
-  local result=$(grep -w "${name}" ${awsEC2list} 2>/dev/null | awk '{print $1}' | head -1)
+  result=$(awk '{print $1,$2}' ${awsEC2list} | grep -wi "${pattern}" 2>/dev/null | head -1)
   if [ -z "$result" ]; then
-    # attempt to find  one instance by pattern
-    cc=$(grep -ci -- "${name}" ${awsEC2list} 2>/dev/null)
-    # if founded only one host
-    if [ ${cc} -eq 1 ]; then
-      local ec2_name=$(grep -i -- ${name} ${awsEC2list} 2>/dev/null | awk '{print $2}')
-      log "Found instance: $ec2_name"
-      result=$(grep ${ec2_name} ${awsEC2list} 2>/dev/null | awk '{print $1}')
-    else
-      warning "No one EC2 found by pattern \"$name\" in project: $Project"
-      ListInstancesByPattern ${name}
-      error "Instance not identified"
-    fi
+    error "No one EC2 found by pattern \"$pattern\" in project: $Project"
   fi
-  GetInstanceResult=$result
+  ec2_id=$(echo $result | awk '{print $1}')
+  ec2_name=$(echo $result | awk '{print $2}')
+  GetInstanceResult=$ec2_id
+  GetInstanceDescription=$ec2_name
 }
 #
 GetSshKeyForInstance() {
   GetCurrentProject
   SetProjectVars
   local ec2_id=$1
+  local result
   if [ -z "${ec2_id}" ]; then
     error "function: GetSshKeyForInstance, parameter is EMPTY"
   fi
-  local result=$(grep ^${ec2_id} ${awsEC2list} 2>/dev/null | awk '{print $4}' | head -1)
+  result=$(grep ^${ec2_id} ${awsEC2list} 2>/dev/null | awk '{print $4}' | head -1)
   if [ -z "$result" ]; then
     error "Ssh key for instance \"$ec2_id\" not found in project: $Project"
   fi
@@ -258,6 +241,7 @@ COMMANDS:
   create : create new project
   lp     : list projects
   sync   : sync EC2 id and Names
+  show   : show current state of all EC2 instances
   ls     : list EC2 instances
   {hostname}     : connect to host by SSM
   ssh {hostname} : connect to host by SSH via SSM Proxy
@@ -272,20 +256,42 @@ Sync() {
   SetProjectVars
   local jsonfile
   jsonfile=$(mktemp)
-  aws ec2 describe-instances --filter Name=tag-key,Values=Name --query 'Reservations[*].Instances[*].{InstanceId:InstanceId,PrivateIp:PrivateIpAddress,sshkey:KeyName,Name:Tags[?Key==`Name`]|[0].Value}' --output json >${jsonfile}
+  aws ec2 describe-instances --filter Name=tag-key,Values=Name --query 'Reservations[*].Instances[*].{InstanceId:InstanceId,PrivateIp:PrivateIpAddress,sshkey:KeyName,InstanceType:InstanceType,Name:Tags[?Key==`Name`]|[0].Value}' --output json >${jsonfile}
   # received error
   local exitcode="$?"
   if [ "${exitcode}" -ne "0" ]; then
-    error "Exit code not zero: ${exitcode}"
-    echo "------ OUTPUT -----------"
+    warning "--- AWS CLI execution error. OUTPUT ---"
     cat ${jsonfile}
     rm -f ${jsonfile}
+    error "AWS CLI Error: ${exitcode}. Can not continue"
   fi
   #
-  cat ${jsonfile} | jq -r '.[] | .[] | "\(.InstanceId) \(.Name) \(.PrivateIp) \(.sshkey)"' >${awsEC2list}
+  cat ${jsonfile} | jq -r '.[] | .[] | "\(.InstanceId) \(.Name) \(.PrivateIp) \(.sshkey) \(.InstanceType)"' >${awsEC2list}
   rm -f ${jsonfile}
   #
   log "EC2 count: $(wc -l ${awsEC2list})"
+  exit 0
+}
+#
+Show() {
+  log "Reading AWS EC2 instances. Please wait..."
+  GetCurrentProject
+  SetProjectVars
+  local jsonfile
+  jsonfile=$(mktemp)
+  aws ec2 describe-instances --filter Name=tag-key,Values=Name --query 'Reservations[*].Instances[*].{InstanceId:InstanceId,PrivateIp:PrivateIpAddress,sshkey:KeyName,InstanceType:InstanceType,Name:Tags[?Key==`Name`]|[0].Value,State:State.Name}' --output json >${jsonfile}
+  # received error
+  local exitcode="$?"
+  if [ "${exitcode}" -ne "0" ]; then
+    warning "--- AWS CLI execution error. OUTPUT ---"
+    cat ${jsonfile}
+    rm -f ${jsonfile}
+    error "AWS CLI Error: ${exitcode}. Can not continue"
+  fi
+  #
+  cat ${jsonfile} | jq -r '.[] | .[] | "\(.InstanceId) \(.Name) \(.PrivateIp) \(.State)"'
+  rm -f ${jsonfile}
+  #
   exit 0
 }
 #
@@ -326,34 +332,39 @@ Info() {
 }
 #
 ConnectSSH() {
-  local instance
+  local ec2_id
+  local ec2_name
   if [ -z "$1" ]; then
     error "No hostname as parameter. Check instance list: ${app} ls"
   fi
   GetInstance $1
-  instance=$GetInstanceResult
+  ec2_id=$GetInstanceResult
+  ec2_name=$GetInstanceDescription
   #
-  GetSshKeyForInstance $instance
+  GetSshKeyForInstance $ec2_id
   ssh_key_ec2=$GetSshKeyForInstance
   #
   local ss="$HOME/.ssh/${Project}/${ssh_key_ec2}"
   if [ -f $ss ]; then
-    log "Connecting via SSH ..."
-    ssh -i $ss ec2-user@${instance}
+    log "Connecting to $ec2_name via SSH ..."
+    ssh -i $ss ec2-user@${ec2_id}
   else
     error "SSH key not found: $ss"
   fi
 }
 #
 ConnectSSM() {
+  local ec2_id
+  local ec2_name
   if [ -z "$1" ]; then
     error "No hostname as parameter. Check instance list: ${app} ls"
   fi
   GetInstance $1
-  instance=$GetInstanceResult
+  ec2_id=$GetInstanceResult
+  ec2_name=$GetInstanceDescription
   #
-  log "Connecting via SSH ..."
-  aws ssm start-session --target ${instance}
+  log "Connecting to $ec2_name via SSM ..."
+  aws ssm start-session --target ${ec2_id}
 }
 #
 ExecDSH() {
@@ -402,6 +413,9 @@ while [ -n "$1" ]; do
   case "$1" in
   sync)
     Sync
+    ;;
+  show)
+    Show
     ;;
   ls)
     ListInstances
