update ShowHelp

diff --git a/bin/awpt b/bin/awpt
--- a/bin/awpt
+++ b/bin/awpt
@@ -222,110 +222,111 @@ GetSshKeyForInstance=$result
 }
 #
 ShowHelp() {
-  echo "AWS Project Tool"
-  echo "Version: $version"
-  echo ""
-  echo "USAGE: ${app} [COMMAND|HOSTNAME]"
-  echo ""
-  echo "COMMANDS:"
-  echo "  info   : show current project"
-  echo "  sp     : set project"
-  echo "  create : create new project"
-  echo "  lp     : list projects"
-  echo "  sync   : sync EC2 id and Names"
-  echo "  ls     : list EC2 instances"
-  echo "  {hostname}     : connect to host by SSM"
-  echo "  ssh {hostname} : connect to host by SSH via SSM Proxy"
-  exit 0
+cat << EOF
+Version: $version
+
+USAGE: ${app} [COMMAND|HOSTNAME]
+
+COMMANDS:
+  info   : show current project
+  sp     : set project
+  create : create new project
+  lp     : list projects
+  sync   : sync EC2 id and Names
+  ls     : list EC2 instances
+  {hostname}     : connect to host by SSM
+  ssh {hostname} : connect to host by SSH via SSM Proxy
+EOF
+exit 0
 }
 #
 Sync() {
-  log "Reading AWS EC2 instances. Please wait..."
-  GetCurrentProject
-  SetProjectVars
-  local jsonfile=$(mktemp)
-  aws ec2 describe-instances --filter Name=tag-key,Values=Name --query 'Reservations[*].Instances[*].{InstanceId:InstanceId,PrivateIp:PrivateIpAddress,sshkey:KeyName,Name:Tags[?Key==`Name`]|[0].Value}' --output json > ${jsonfile}
-  # received error
-  local exitcode="$?"
-  if [ "${exitcode}" -ne "0" ]; then
-    error "Exit code not zero: ${exitcode}"
-    echo "------ OUTPUT -----------"
-    cat ${jsonfile}
-    rm -f ${jsonfile}
-  fi
-  #
-  cat ${jsonfile} | jq -r '.[] | .[] | "\(.Name) \(.InstanceId) \(.sshkey) \(.PrivateIp)"' > ${awsEC2list}
+log "Reading AWS EC2 instances. Please wait..."
+GetCurrentProject
+SetProjectVars
+local jsonfile=$(mktemp)
+aws ec2 describe-instances --filter Name=tag-key,Values=Name --query 'Reservations[*].Instances[*].{InstanceId:InstanceId,PrivateIp:PrivateIpAddress,sshkey:KeyName,Name:Tags[?Key==`Name`]|[0].Value}' --output json > ${jsonfile}
+# received error
+local exitcode="$?"
+if [ "${exitcode}" -ne "0" ]; then
+  error "Exit code not zero: ${exitcode}"
+  echo "------ OUTPUT -----------"
+  cat ${jsonfile}
   rm -f ${jsonfile}
-  #
-  log "EC2 count: " $(wc -l ${awsEC2list})
-  exit 0
+fi
+#
+cat ${jsonfile} | jq -r '.[] | .[] | "\(.Name) \(.InstanceId) \(.sshkey) \(.PrivateIp)"' > ${awsEC2list}
+rm -f ${jsonfile}
+#
+log "EC2 count: " $(wc -l ${awsEC2list})
+exit 0
 }
 #
 ListInstances() {
-  GetCurrentProject
-  SetProjectVars
-  if [ -f ${awsEC2list} ]; then
-    local ll=$(wc -l ${awsEC2list} | awk '{print $1}' )
-    if [ "$ll" -eq "0" ]; then
-      error "File with EC2 list (${awsEC2list}) is empty"
-    else
-      sort ${awsEC2list}
-    fi
+GetCurrentProject
+SetProjectVars
+if [ -f ${awsEC2list} ]; then
+  local ll=$(wc -l ${awsEC2list} | awk '{print $1}' )
+  if [ "$ll" -eq "0" ]; then
+    error "File with EC2 list (${awsEC2list}) is empty"
   else
-    error "EC2 list file (${awsEC2list}) does not exists. Execute command first: ${app} sync"
+    sort ${awsEC2list}
   fi
-  exit 0
+else
+  error "EC2 list file (${awsEC2list}) does not exists. Execute command first: ${app} sync"
+fi
+exit 0
 }
 #
 Info() {
-  echo "${app^^} version: $version"
-  GetCurrentProject
-  SetProjectVars
-  if [ -z $Project ]; then
-    error "Current project: not selected"
+echo "${app^^} version: $version"
+GetCurrentProject
+SetProjectVars
+if [ -z $Project ]; then
+  error "Current project: not selected"
+else
+  echo "Current Project: $Project"
+  echo -e "Config file: $ProjectConfig\n-----------"
+  cat $ProjectConfig | grep -v ^#
+  echo "-----------"
+  if [ -f ${awsEC2list} ]; then
+    local ll=$(wc -l ${awsEC2list} | awk '{print $1}' )
+    echo "EC2 count: $ll"
   else
-    echo "Current Project: $Project"
-    echo -e "Config file: $ProjectConfig\n---------"
-    cat $ProjectConfig | grep -v ^#
-    echo "-----------"
-    if [ -f ${awsEC2list} ]; then
-      local ll=$(wc -l ${awsEC2list} | awk '{print $1}' )
-      echo "EC2 count: $ll"
-    else
-      warning "EC2 list file (${awsEC2list}) does not exists. Execute command first: awpt sync"
-    fi
+    warning "EC2 list file (${awsEC2list}) does not exists. Execute command first: awpt sync"
   fi
+fi
 }
 GetSshKeyForInstance() {
-  GetCurrentProject
-  SetProjectVars
-  local name=$1
-  if [ -z "${name}" ]; then
-    error "function: GetSshKeyForInstance, parameter is EMPTY"
-  fi
-  local result=$(grep ^${name} ${awsEC2list} 2>/dev/null | awk '{print $3}'| head -1 )
-  if [ -z "$result" ]; then
-    error "Instance [$name] not found in project [$Project]"
-  fi
-  GetSshKeyForInstance=$result
+GetCurrentProject
+SetProjectVars
+local name=$1
+if [ -z "${name}" ]; then
+  error "function: GetSshKeyForInstance, parameter is EMPTY"
+fi
+local result=$(grep ^${name} ${awsEC2list} 2>/dev/null | awk '{print $3}'| head -1 )
+if [ -z "$result" ]; then
+  error "Instance [$name] not found in project [$Project]"
+fi
+GetSshKeyForInstance=$result
 }
 #
 ConnectSSH() {
-  if [ -z "$1" ]; then
-    error "No hostname as parameter. Check instance list: ${app} ls"
-  fi
-  GetInstance $1
-  instance=$GetInstanceResult
-  #
-  GetSshKeyForInstance $1
-  ssh_key_ec2=$GetSshKeyForInstance
-  #
-  local ss="$HOME/.ssh/${Project}/${ssh_key_ec2}"
-  if [ -f $ss ]; then
-    ssh -i $ss ec2-user@${instance}
-  else
-    error "SSH key not found: $ss"
-  fi
+if [ -z "$1" ]; then
+  error "No hostname as parameter. Check instance list: ${app} ls"
+fi
+GetInstance $1
+instance=$GetInstanceResult
+#
+GetSshKeyForInstance $1
+ssh_key_ec2=$GetSshKeyForInstance
+#
+local ss="$HOME/.ssh/${Project}/${ssh_key_ec2}"
+if [ -f $ss ]; then
+  ssh -i $ss ec2-user@${instance}
+else
+  error "SSH key not found: $ss"
+fi
 }
 #
 ConnectSSM() {
